from __future__ import annotations

import io
from datetime import datetime
from typing import List

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import (
    HRFlowable,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)
from sqlalchemy.orm import Session, joinedload

from app.models import Evaluation, RubricDomain, RubricItem, Score, Task, TaskStatus, User


def generate_evaluation_pdf(db: Session, eval_obj: Evaluation, current_user: User) -> io.BytesIO:
    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf,
        pagesize=letter,
        rightMargin=0.75 * inch,
        leftMargin=0.75 * inch,
        topMargin=0.75 * inch,
        bottomMargin=0.75 * inch,
    )

    styles = getSampleStyleSheet()
    h1 = styles["Heading1"]
    h2 = styles["Heading2"]
    h3 = styles["Heading3"]
    body = styles["BodyText"]
    small = ParagraphStyle("small", parent=body, fontSize=8)
    score_style = ParagraphStyle("score", parent=body, fontSize=9)

    elements = []

    # ── Cover ──────────────────────────────────────────────────────────────────
    elements.append(Paragraph("RubricOps — Cybersecurity Evaluation Report", h1))
    elements.append(Spacer(1, 0.1 * inch))
    elements.append(HRFlowable(width="100%", thickness=2, color=colors.HexColor("#1a56db")))
    elements.append(Spacer(1, 0.15 * inch))

    meta = [
        ["Evaluation:", eval_obj.title],
        ["Period:", f"{eval_obj.period_start.date()} — {eval_obj.period_end.date()}"],
        ["Status:", eval_obj.status.value.upper()],
        ["Generated:", datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")],
        ["Generated by:", current_user.name],
    ]
    meta_table = Table(meta, colWidths=[1.5 * inch, 5 * inch])
    meta_table.setStyle(TableStyle([
        ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("TOPPADDING", (0, 0), (-1, -1), 3),
    ]))
    elements.append(meta_table)
    elements.append(Spacer(1, 0.3 * inch))

    # ── Load scores ────────────────────────────────────────────────────────────
    scores = (
        db.query(Score)
        .join(RubricItem)
        .join(RubricDomain)
        .filter(Score.evaluation_id == eval_obj.id)
        .options(joinedload(Score.rubric_item).joinedload(RubricItem.domain))
        .order_by(RubricDomain.sort_order, RubricItem.sort_order)
        .all()
    )

    # Group by domain
    domain_map: dict = {}
    for s in scores:
        d = s.rubric_item.domain
        domain_map.setdefault(d.id, {"domain": d, "scores": []})
        domain_map[d.id]["scores"].append(s)

    # ── Executive Summary ──────────────────────────────────────────────────────
    elements.append(Paragraph("Executive Summary — Domain Averages", h2))
    elements.append(Spacer(1, 0.1 * inch))

    summary_data = [["Domain", "Avg Maturity (1–5)", "Scored Items", "Unscored"]]
    for data in domain_map.values():
        d = data["domain"]
        s_list = data["scores"]
        scored = [s.maturity_level for s in s_list if s.maturity_level > 0]
        unscored = len(s_list) - len(scored)
        avg = f"{sum(scored) / len(scored):.1f}" if scored else "—"
        summary_data.append([d.name, avg, len(scored), unscored])

    sum_table = Table(summary_data, colWidths=[3 * inch, 1.8 * inch, 1.2 * inch, 0.8 * inch])
    sum_table.setStyle(_table_style(header_color=colors.HexColor("#1a56db")))
    elements.append(sum_table)
    elements.append(Spacer(1, 0.3 * inch))

    # ── Detailed Scores ────────────────────────────────────────────────────────
    elements.append(Paragraph("Detailed Scores by Domain", h2))

    for data in domain_map.values():
        d = data["domain"]
        elements.append(Spacer(1, 0.15 * inch))
        elements.append(Paragraph(d.name, h3))
        if d.description:
            elements.append(Paragraph(d.description, small))
        elements.append(Spacer(1, 0.08 * inch))

        detail_data = [["Code", "Control", "Level", "Confidence", "Rationale"]]
        for s in data["scores"]:
            item = s.rubric_item
            level_str = str(s.maturity_level) if s.maturity_level > 0 else "—"
            rationale = (s.rationale or "")[:120]
            detail_data.append([
                item.code,
                Paragraph(item.title, score_style),
                level_str,
                s.confidence.value if s.confidence else "—",
                Paragraph(rationale, score_style),
            ])

        det_table = Table(detail_data, colWidths=[0.6 * inch, 2.2 * inch, 0.5 * inch, 0.8 * inch, 2.6 * inch])
        det_table.setStyle(_table_style(header_color=colors.HexColor("#374151")))
        elements.append(det_table)

    elements.append(Spacer(1, 0.3 * inch))

    # ── Action Plan ────────────────────────────────────────────────────────────
    open_tasks = (
        db.query(Task)
        .filter(Task.evaluation_id == eval_obj.id, Task.status != TaskStatus.done)
        .all()
    )
    if open_tasks:
        elements.append(Paragraph("Action Plan", h2))
        elements.append(Spacer(1, 0.1 * inch))
        task_data = [["Title", "Status", "Due Date"]]
        for t in open_tasks:
            task_data.append([
                Paragraph(t.title, score_style),
                t.status.value,
                t.due_date.strftime("%Y-%m-%d") if t.due_date else "—",
            ])
        task_table = Table(task_data, colWidths=[4.5 * inch, 1.0 * inch, 1.2 * inch])
        task_table.setStyle(_table_style(header_color=colors.HexColor("#d97706")))
        elements.append(task_table)

    doc.build(elements)
    buf.seek(0)
    return buf


def _table_style(header_color=colors.grey) -> TableStyle:
    return TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), header_color),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 8),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f3f4f6")]),
        ("GRID", (0, 0), (-1, -1), 0.25, colors.HexColor("#d1d5db")),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ("LEFTPADDING", (0, 0), (-1, -1), 5),
    ])
